import json, os, subprocess, requests
from datetime import datetime

GITHUB_TOKEN = os.environ["GH_PAT"]
REPO = os.environ["GITHUB_REPOSITORY"]
BASE_BRANCH = "main"

def git(cmd, cwd=None):
    subprocess.run(cmd, shell=True, check=True, cwd=cwd)

def create_pr(branch, title, body):
    resp = requests.post(
        f"https://api.github.com/repos/{REPO}/pulls",
        json={"title": title, "body": body, "head": branch, "base": BASE_BRANCH},
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github+json",
        }
    )
    resp.raise_for_status()
    return resp.json()["html_url"]

if __name__ == "__main__":
    with open("fix_summary.json") as f:
        summary = json.load(f)

    applied = summary["applied"]
    if not applied:
        print("Nothing to commit.")
        exit(0)

    app_dir = "target-app" if os.path.exists("target-app") else "."
    branch = f"fix/trivy-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    cves = ", ".join(set(f["cve"] for f in applied))

    git(f'git config user.email "security-bot@ci"', cwd=app_dir)
    git(f'git config user.name "Security Bot"', cwd=app_dir)
    git(f"git checkout -b {branch}", cwd=app_dir)

    for f in ["package.json", "package-lock.json", "yarn.lock", "requirements.txt"]:
        if os.path.exists(os.path.join(app_dir, f)):
            git(f"git add {f}", cwd=app_dir)

    result = subprocess.run("git diff --cached --name-only", shell=True, capture_output=True, text=True, cwd=app_dir)
    if not result.stdout.strip():
        print("No changes to commit.")
        exit(0)

    git(f'git commit -m "fix(security): auto-fix {len(applied)} Trivy vulnerabilities\n\nCVEs: {cves}"', cwd=app_dir)

    # ← Pusher vers TON FORK, pas vers le repo original
    import re
    repo_url = os.environ.get("REPO_URL", "")
    match = re.search(r"github\.com[:/](.+)/(.+?)(?:\.git)?$", repo_url)
    repo_name = match.group(2) if match else "repo"
    github_actor = os.environ.get("GITHUB_ACTOR", "YoussefHalleb")  # ton username

    fork_url = f"https://x-access-token:{GITHUB_TOKEN}@github.com/{github_actor}/{repo_name}.git"
    git(f"git remote add fork {fork_url}", cwd=app_dir)
    git(f"git push fork {branch}", cwd=app_dir)

    # PR de ton fork → repo original
    original_repo = f"{match.group(1)}/{repo_name}" if match else REPO
    resp = requests.post(
        f"https://api.github.com/repos/{original_repo}/pulls",
        json={
            "title": f"fix(security): auto-fix {len(applied)} vulnerabilities [{cves}]",
            "body": "\n".join([
                "## 🤖 Automated Security Fix\n",
                "Generated by Groq AI from Trivy scan.\n",
                *[f"- **{f['pkg']}** — {f['cve']}: `{f['cmd']}`" for f in applied]
            ]),
            "head": f"{github_actor}:{branch}",  # ← format fork:branch
            "base": BASE_BRANCH
        },
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github+json",
        }
    )
    resp.raise_for_status()
    pr_url = resp.json()["html_url"]
    print(f"✅ PR created: {pr_url}")
