import json, os, subprocess, requests
from datetime import datetime

GITHUB_TOKEN = os.environ["GH_PAT"]
REPO = os.environ["GITHUB_REPOSITORY"]  # owner/repo
BASE_BRANCH = "main"

def git(cmd):
    subprocess.run(cmd, shell=True, check=True)

def create_pr(branch, title, body):
    resp = requests.post(
        f"https://api.github.com/repos/{REPO}/pulls",
        json={"title": title, "body": body, "head": branch, "base": BASE_BRANCH},
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github+json",
        }
    )
    resp.raise_for_status()
    return resp.json()["html_url"]

if __name__ == "__main__":
    with open("fix_summary.json") as f:
        summary = json.load(f)

    applied = summary["applied"]
    if not applied:
        print("Nothing to commit.")
        exit(0)

    branch = f"fix/trivy-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    cves = ", ".join(set(f["cve"] for f in applied))
    
    git(f'git config user.email "security-bot@ci"')
    git(f'git config user.name "Security Bot"')
    git(f"git checkout -b {branch}")
    git(f"git add package.json package-lock.json yarn.lock requirements.txt 2>/dev/null || true")
    git(f'git commit -m "fix(security): auto-fix {len(applied)} Trivy vulnerabilities\n\nCVEs: {cves}"')
    git(f"git push origin {branch}")

    body_lines = ["## 🤖 Automated Security Fix\n", "Generated by Claude AI from Trivy scan.\n"]
    for f in applied:
        body_lines.append(f"- **{f['pkg']}** — {f['cve']}: `{f['cmd']}`")
    
    pr_url = create_pr(branch, f"fix(security): auto-fix {len(applied)} vulnerabilities [{cves}]", "\n".join(body_lines))
    print(f"PR created: {pr_url}")
