env:
  contexts:
    - name: AuthenticatedContext
      urls:
        - http://app-under-test:3000

      includePaths:
        - http://app-under-test:3000.*

      excludePaths: []

      sessionManagement:
        method: cookie

      authentication:
        method: form
        parameters:
          loginPageUrl: http://app-under-test:3000/login
          loginRequestUrl: http://app-under-test:3000/login
          loginRequestBody: username={%username%}&password={%password%}
        verification:
          method: response
          loggedInRegex: "Logout|Dashboard|Profile"
          loggedOutRegex: "Login"

      users:
        - name: testuser
          credentials:
            username: admin
            password: admin123

jobs:

  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 0

  - type: spider
    parameters:
      context: AuthenticatedContext
      user: testuser
      url: http://app-under-test:3000
      maxDuration: 10

  # IMPORTANT pour SPA comme Juice Shop
  - type: spiderAjax
    parameters:
      context: AuthenticatedContext
      user: testuser
      url: http://app-under-test:3000
      maxDuration: 10

  # Scan complet (corrige ton problème principal)
  - type: activeScan
    parameters:
      context: AuthenticatedContext
      user: testuser
      url: http://app-under-test:3000
      maxScanDurationInMins: 30

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: zap.html

  - type: report
    parameters:
      template: traditional-xml
      reportDir: /zap/wrk
      reportFile: zap.xml
