name: Universal 

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
    inputs:
      scan_url:
        description: "URL à scanner (par défaut http://wackopicko.com)"
        required: false
        default: "http://wackopicko.com"

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      SCAN_URL: ${{ github.event.inputs.scan_url }}
      BACKEND_URL: https://35.195.231.227.nip.io

    steps:

    # Checkout the repository
    - name: Checkout pipeline repository
      uses: actions/checkout@v4

    # ====================================
    # Wait for Application to be up
    # ====================================
    - name: Wait for Application
      run: |
        echo "=== Checking if the application is reachable ==="
        curl -v $SCAN_URL || exit 1

    # ====================================
    # OWASP ZAP Scan (DAST)
    # ====================================
    - name: OWASP ZAP Full Scan
      run: |
        docker run --rm \
        --user root \
        -v "$(pwd)":/zap/wrk \
        ghcr.io/zaproxy/zaproxy:stable \
        zap-full-scan.py \
        -t $SCAN_URL \
        -x zap.xml \
        -r zap.html \
        -j \
        -z "-config scanner.attackStrength=MEDIUM" || true

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # Install dependencies
    - name: Install dependencies
      run: pip install requests

    # ====================================
    # Upload to DefectDojo
    # ====================================
    - name: Upload to DefectDojo
      run: python defectdojo_upload.py
      env:
        DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
        DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}

    # ====================================
    # Upload Security Reports
    # ====================================
    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          zap.xml
          zap.html

    # Upload ZAP Report to Backend
    - name: Upload ZAP Report to Backend
      run: |
        curl -X POST "${{ env.BACKEND_URL }}/api/products/upload-zap" \
        -F "report=@zap.html"
