name: Juice Shop ZAP Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start Juice Shop
        run: |
          docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop:latest
          sleep 20

      - name: Create ZAP context with login
        run: |
          cat <<EOF > zap_login.context
          {
            "context": {"name": "JuiceShopContext"},
            "users": [
              {
                "name": "admin",
                "credentials": {"email":"admin@juice-sh.op","password":"admin123"}
              }
            ],
            "authentication": {
              "method": "form",
              "loginPageUrl": "http://localhost:3000/#/login",
              "loginRequestUrl": "http://localhost:3000/rest/user/login",
              "loginRequestBody": "{\"email\":\"admin@juice-sh.op\",\"password\":\"admin123\"}"
            }
          }
          EOF

      - name: Run OWASP ZAP scan
        run: |
          docker run --rm --user root -v "$(pwd)/zap_reports:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py \
            -t http://host.docker.internal:3000 \
            -t http://host.docker.internal:3000/rest/user \
            -c /zap/wrk/zap_login.context \
            -r zap_report.html \
            -J zap_report.json

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_reports/
